clearvars;

case_names = {'all10', 'all20', 'all30', 'all40', 'all50', 'all10a'};
test_paths = {'test_img/auto10/', 'test_img/auto20/', 'test_img/auto30/', ...
    'test_img/auto40/', 'test_img/auto50/', 'test_img/auto50/'};

% methods = {
%     {'hao', 'hao', 23} ...
%     ,{'gradient', 'hao', 20} ...
%     ,{'hao', 'geomGradient', 20} ...
%     ,{'gradient', 'geomGradient', 21} ...
%     ,{'gradient', 'angle', 16} ...
%     ,{'hao', 'angle', 14}
%     };

methods = {
    {'hao', 'hao', 30} ...
    ,{'gradient', 'hao', 27} ...
    ,{'hao', 'geomGradient', 27} ...
    ,{'gradient', 'geomGradient', 29} ...
    ,{'gradient', 'angle', 23} ...
    ,{'hao', 'angle', 21}
    };

% methods = {{'hao', 'exhaust', 7}, ...
%             {'sm', 'exhaust', 7}, ...
%             {'ipfp', 'exhaust', 7}, ...
%             {'rrwm', 'exhaust', 7}, ...
%             {'gradient', 'exhaust', 7}};

warning('OFF', 'all');

for i = 1 : 6
    m = methods{i};
    options.local = m{1};
    options.global = m{2};
    options.min_inl_count = m{3};
    for j = 6 : 6
        test(case_names{j}, test_paths{j}, false, false, 1, 50, 1, options);
%         test(case_names{j}, test_paths{j}, true, true, 1, 50, 1, options);
%         test(case_names{j}, test_paths{j}, true, true, 1, 50, 1, options);
    end
    fprintf('\n\n');
end

warning('ON', 'all');
